apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    app: broker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: jefersson12/microservice-broker:latest
          ports:
            - containerPort: 8082
          env:
            - name: ENV_VARIABLE
              value: "example_value"
