apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger
  labels:
    app: logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
        - name: logger
          image: jefersson12/microservice-logger:latest # Cambiar por tu imagen
          ports:
            - containerPort: 8084
          env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://mongo:password@mongo:27017/logs_db"
