apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp  # Nombre único para el puerto AMQP
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management  # Nombre único para el puerto de administración
      protocol: TCP
      port: 15672
      targetPort: 15672
